# GitHub Sponsors Configuration for FlexDoc

github: [rakeshwfg]

# You can also add other platforms:
# patreon: your-username
# open_collective: flexdoc
# ko_fi: your-username
# custom: ["https://flexdoc.dev/sponsor"]
