# FlexDoc API Docker Compose Configuration

version: '3.8'

services:
  flexdoc-api:
    build: .
    image: flexdoc-api:latest
    container_name: flexdoc-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      # Optional: Enable authentication
      # - ENABLE_AUTH=true
      # - API_KEY=your-secret-api-key-here
      # Optional: CORS configuration
      # - CORS_ORIGINS=https://example.com,https://app.example.com
      # Optional: Rate limiting
      # - RATE_LIMIT_WINDOW_MS=900000
      # - RATE_LIMIT_MAX=100
      # Optional: Job retention (in milliseconds)
      # - JOB_RETENTION_MS=3600000
    volumes:
      - uploads:/app/uploads
      - outputs:/app/outputs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits (optional but recommended for production)
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  uploads:
  outputs:

networks:
  default:
    name: flexdoc-network
